name: CDB repository sync
on:
  push:
    branches:
      - main
jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      REMOTE: YGOProjectUnderground/Nexus.git
      DESTINATION: Nexus
    steps:
    - uses: actions/checkout@v1
    - name: Clone destination repository
      run: |
        cd $HOME
        git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/$REMOTE
        mkdir -p $DESTINATION
    - name: Copy all modified and new CDBs
      run: |
        FILES=$(git diff-tree --no-commit-id --name-only -r HEAD --diff-filter=AM | grep ".cdb$" || [[ $? == 1 ]])
        if [[ "$FILES" ]]; then
          rsync -avR $FILES $HOME/$DESTINATION
        fi
    - name: Remove deleted files
      run: |
        if [[ -f $HOME/$DESTINATION/VERSION ]]; then
          LAST_SHA=$(cat $HOME/$DESTINATION/VERSION)
          REMOVED=$(git diff --name-only --no-renames --diff-filter=D $LAST_SHA)
          if [[ "$REMOVED" ]]; then
            cd $HOME/$DESTINATION
            git rm -rf --ignore-unmatch $REMOVED
          fi
        fi
    - name: Commit and push with original metadata
      run: |
        MESSAGE=$(git log -1 --pretty=%B)
        AUTHOR=$(git log -1 --pretty=format:'%an')
        EMAIL=$(git log -1 --pretty=format:'%ae')
        COMMITTER=$(git log -1 --pretty=format'%cn')
        CEMAIL=$(git log -1 --pretty=format:'%ce')
        cd $HOME/$DESTINATION
        git config user.email "$CEMAIL"
        git config user.name "$COMMITTER"
        git add -A .
        if [[ $(git status --porcelain) ]]; then
          echo $GITHUB_SHA > VERSION
          git add -A .
          git commit --author="$AUTHOR <$EMAIL>" -m "$MESSAGE"
          git push
        fi